spring.datasource.url=jdbc:postgresql://localhost:5432/acebook_springboot_development
spring.datasource.username=
spring.datasource.password=
flyway.baseline-on-migrate=true
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

okta.oauth2.issuer=https://dev-7vrk5hcpus8z0c4s.us.auth0.com/
okta.oauth2.client-id=Ie2acua0hzJvwfC7SNMqJsgf9GbVodvw
okta.oauth2.client-secret=0kijTkFWcUhfFU_AHPDg8DVd09uX0kz0AV25icPSMsWUXN_f0qTqyVbQLiIXE23M